//
// ArticleList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ArticleList: Codable {

    public var status: String?
    public var totalResults: Int?
    public var articles: [Article]?

    public init(status: String?, totalResults: Int?, articles: [Article]?) {
        self.status = status
        self.totalResults = totalResults
        self.articles = articles
    }


}

